### ISSUE TITLE
Bug: Getting a Surreal is not a constructor although i've gotte 

### ISSUE THREAD

**Issue by Benbellah-Owino** [surrealdb/surrealdb.node#24]
### Describe the bug
```js
const { default: Surreal } = require('surrealdb.node');

const db = new Surreal();

async function connect_surreal_db(){
   
    try {
        await db.connect('http://127.0.0.1:8080/rpc');

        await db.signin({
            username: process.env.DB_USERNAME,
            password: process.env.DB_PASSWORD
        });

        await db.use({namespace:'EVENT_CONTRACT', database:'event_db1'});


    } catch (error) {
        return new Error("Database connection failed");
    }
}
```
### Steps to reproduce

1. I installed the nodejs sdk
2. I copied your docs word for word bar for bar
3. It crashes

### Expected behaviour

To connect to the database

### SurrealDB version

1.0.0

### Contact Details

owinobenbellah@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
@Ekwuno could we for the moment change the `{ default: Surreal }` bit in the docs (only for NodeJS) to `{ Surreal }`?

**Comment by CanRau** [comment]
I think named exports are preferable anyway, but if it makes sense having both should be fine too I guess 🤷🏼

**Comment by kearfy** [comment]
Absolutely, but it does not hurt to have a default export too :)

**Comment by Ekwuno** [comment]
resolved  by https://github.com/surrealdb/docs.surrealdb.com/pull/487
