### ISSUE TITLE
having hard time to connect my server node js with surreal

### ISSUE THREAD

**Issue by barel-mishal** [surrealdb/surrealdb.node#3]
Hello Surreal team,

I am trying out your database but having a hard time making it work with my express server. 
is there any tutorial on using your surreal with node except for the documentation?

**Comment by AidanTilgner** [comment]
@barel-mishal hey I'm not sure if you ended up getting help on this. Looks like the docs for a Surreal setup in a node app are [here](https://surrealdb.com/docs/integration/libraries/nodejs). This goes into detail on how to implement the [surrealdb.js](https://github.com/surrealdb/surrealdb.js) driver in a node app. Hope I could help, I ran into the same issue setting up my own express app with surreal, seems like docs are limited right now.
